const developers = JSON.parse([
  {
    id: "1512530",
    name: "Letty Pariss",
    email: "lpariss0@diigo.com",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/76.jpg",
    charge_per_hour: "$33.34",
    specialist: "Front-End",
  },
  {
    id: "0104808",
    name: "Clio Hedditeh",
    email: "chedditeh1@mayoclinic.com",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/54.jpg",
    charge_per_hour: "$49.71",
    specialist: "Front-End",
  },
  {
    id: "8335699",
    name: "Hersh Gligorijevic",
    email: "hgligorijevic2@sina.com.cn",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    charge_per_hour: "$36.12",
    specialist: "Node Js",
  },
  {
    id: "7258226",
    name: "Mechelle Lebourn",
    email: "mlebourn3@cisco.com",
    gender: "male",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    charge_per_hour: "$34.77",
    specialist: "Mongo Db",
  },
  {
    id: "11-1440819",
    name: "Carrissa Bradbury",
    email: "cbradbury4@bizjournals.com",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/89.jpg",
    charge_per_hour: "$39.61",
    specialist: "Javascript",
  },
  {
    id: "91-3839378",
    name: "Tobit Zeale",
    email: "tzeale5@jiathis.com",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/men/68.jpg",
    charge_per_hour: "$34.87",
    specialist: "React Front-End",
  },
  {
    id: "14-1891241",
    name: "Blair Kmicicki",
    email: "bkmicicki6@ovh.net",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    charge_per_hour: "$40.93",
    specialist: "Graphics Design",
  },
  {
    id: "53-9886771",
    name: "Raimund Scotchford",
    email: "rscotchford7@gizmodo.com",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    charge_per_hour: "$46.67",
    specialist: "UI/UX",
  },
  {
    id: "75-5504442",
    name: "Lindsey Lowndsbrough",
    email: "llowndsbrough8@cam.ac.uk",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    charge_per_hour: "$47.58",
    specialist: "Data Structure",
  },
  {
    id: "05-7025971",
    name: "Bobbette Baitson",
    email: "bbaitson9@economist.com",
    gender: "Female",
    charge_per_hour: "$33.28",
    avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    specialist: "React SPA",
  },
  {
    id: "85-8287216",
    name: "Drona Hagstone",
    email: "dhagstonea@timesonline.co.uk",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/82.jpg",
    charge_per_hour: "$31.84",
    specialist: "Full Stack",
  },
  {
    id: "94-5512701",
    name: "Linell Reyes",
    email: "lreyesb@livejournal.com",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    charge_per_hour: "$49.02",
    specialist: "Mern Stack",
  },
]);

console.log(developers);
