const developers = JSON.parse([
  {
    id: "1512530",
    name: "Letty Pariss",
    email: "lpariss0@diigo.com",
    avatar: "https://randomuser.me/api/portraits/men/76.jpg",
    hourly_charge: 73.34,
    specialist: "Front-End",
    times_hired: 69,
  },
  {
    id: "0104808",
    name: "Clio Hdditeh",
    email: "chedditeh1@mayoclinic.com",
    avatar: "https://randomuser.me/api/portraits/men/54.jpg",
    hourly_charge: 69.71,
    specialist: "Front-End",
    times_hired: 101,
  },
  {
    id: "8335699",
    name: "Hersh Gligorijevic",
    email: "hgligorijevic2@sina.com.cn",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    hourly_charge: 56.12,
    specialist: "Node Js",
    times_hired: 96,
  },
  {
    id: "7258226",
    name: "Mechelle Lebourn",
    email: "mlebourn3@cisco.com",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    hourly_charge: 74.77,
    specialist: "Mongo Db",
    times_hired: 83,
  },
  {
    id: "11-1440819",
    name: "Carrissa Bradbury",
    email: "cbradbury4@bizjournals.com",
    avatar: "https://randomuser.me/api/portraits/men/89.jpg",
    hourly_charge: 65.61,
    specialist: "Javascript",
    times_hired: 85,
  },
  {
    id: "91-3839378",
    name: "Tobit Zeale",
    email: "tzeale5@jiathis.com",
    avatar: "https://randomuser.me/api/portraits/men/68.jpg",
    hourly_charge: 74.87,
    specialist: "React Front-End",
    times_hired: 83,
  },
  {
    id: "14-1891241",
    name: "Blair Kmicicki",
    email: "bkmicicki6@ovh.net",
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    hourly_charge: 85.93,
    specialist: "Graphics Design",
    times_hired: 95,
  },
  {
    id: "53-9886771",
    name: "Raimund Scotchford",
    email: "rscotchford7@gizmodo.com",
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    hourly_charge: 52.67,
    specialist: "UI/UX",
    times_hired: 26,
  },
  {
    id: "75-5504442",
    name: "Lindsey Lowndsbrough",
    email: "llowndsbrough8@cam.ac.uk",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    hourly_charge: 85.58,
    specialist: "Data Structure",
    times_hired: 68,
  },
  {
    id: "05-7025971",
    name: "Bobbette Baitson",
    email: "bbaitson9@economist.com",
    hourly_charge: 78.28,
    avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    specialist: "React SPA",
    times_hired: 84,
  },
  {
    id: "85-8287216",
    name: "Drona Hagstone",
    email: "dhagstonea@timesonline.co.uk",
    avatar: "https://randomuser.me/api/portraits/men/82.jpg",
    hourly_charge: 49.84,
    specialist: "Full Stack",
    times_hired: 46,
  },
  {
    id: "94-5512701",
    name: "Linell Reyes",
    email: "lreyesb@livejournal.com",

    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    hourly_charge: 54.02,
    specialist: "Mern Stack",
    times_hired: 78,
  },
]);

console.log(developers);
